Staging
pastelnetwork/pastel-explorer-frontend pull request #105
Opened 2021-07-20 11:03 UTC by westalert

merge request from staging to master

2021-07-20 17:36 UTC, CrazyOptimist requested changes

2021-07-20 17:36 UTC, CrazyOptimist commented on src/components/InfinityTable/InfinityTable.tsx
> +    () => (isDarkMode ? ['#232630', 0.5] : ['#FFFFFF', 0.05]),
Please use colors from theme, as hardcoding colors looks not very good

2021-07-20 17:36 UTC, CrazyOptimist commented on src/components/SearchBar/SwitchMode.tsx
> +        style={{ color: isDarkMode ? '#F8F8FA' : '#2D3748' }}
Use colors from theme

2021-07-20 17:36 UTC, CrazyOptimist commented on src/components/Sidebar/Sidebar.tsx
> +              <IconButton target="_blank" href={url} style={{ color: '#6151d0', padding: '4px' }}>
If it's complex to use color from theme, consider defining and using css variables, they can be changed by dark mode as well.
But I guess theme should be enough for managing colors, isn't it?

2021-07-20 17:36 UTC, CrazyOptimist commented on src/pages/HistoricalStatistics/BlockchainSize/index.tsx
> +        params: { period, sortDirection: 'DESC', sqlQuery: 'SUM(size)' },
`sqlQuery` here should be changed to not pass sql directly. Maybe such parameter will fit: `aggregate: 'sumSize'`

2021-07-20 17:36 UTC, CrazyOptimist commented on src/pages/HistoricalStatistics/Difficulty/index.tsx
> +  });
I can see no loading and no error handling here,
I suggest to use `react-query`: it takes care of caching, provide loading and error state.

2021-07-21 21:16 UTC, CrazyOptimist submitted a review, later dismissed

2021-07-22 21:54 UTC, Dicklesworthstone submitted a review, later dismissed

2021-07-29 18:11 UTC, CrazyOptimist approved these changes

2021-08-06 07:56 UTC, Dicklesworthstone approved these changes

2021-08-06 07:58 UTC, merged